BEGIN;

CREATE SCHEMA IF NOT EXISTS gradience;
SET search_path TO gradience, public;

DO $$
BEGIN
    IF NOT EXISTS (SELECT 1 FROM pg_type WHERE typname = 'user_status') THEN
        CREATE TYPE user_status AS ENUM ('active', 'inactive', 'invited');
    END IF;
    IF NOT EXISTS (SELECT 1 FROM pg_type WHERE typname = 'course_membership_role') THEN
        CREATE TYPE course_membership_role AS ENUM ('grader', 'student');
    END IF;
    IF NOT EXISTS (SELECT 1 FROM pg_type WHERE typname = 'course_membership_status') THEN
        CREATE TYPE course_membership_status AS ENUM ('active', 'dropped');
    END IF;
    IF NOT EXISTS (SELECT 1 FROM pg_type WHERE typname = 'assignment_type') THEN
        CREATE TYPE assignment_type AS ENUM ('written', 'programming', 'multiple_choice');
    END IF;
    IF NOT EXISTS (SELECT 1 FROM pg_type WHERE typname = 'submission_status') THEN
        CREATE TYPE submission_status AS ENUM ('submitted', 'late', 'resubmitted', 'graded');
    END IF;
    IF NOT EXISTS (SELECT 1 FROM pg_type WHERE typname = 'ai_processed_status') THEN
        CREATE TYPE ai_processed_status AS ENUM ('awaiting', 'processing', 'done', 'failed');
    END IF;
    IF NOT EXISTS (SELECT 1 FROM pg_type WHERE typname = 'grading_assignment_status') THEN
        CREATE TYPE grading_assignment_status AS ENUM ('pending', 'in_progress', 'completed', 'regraded');
    END IF;
    IF NOT EXISTS (SELECT 1 FROM pg_type WHERE typname = 'comment_type') THEN
        CREATE TYPE comment_type AS ENUM ('inline', 'summary');
    END IF;
END
$$;

CREATE TABLE IF NOT EXISTS users (
    id                    bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    first_name            text NOT NULL,
    last_name             text NOT NULL,
    email                 text NOT NULL UNIQUE,
    password_hash         text NOT NULL,
    auth_provider_id      text,
    created_at            timestamptz NOT NULL DEFAULT now(),
    status                user_status NOT NULL DEFAULT 'invited'
);

CREATE TABLE IF NOT EXISTS courses (
    id                    bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    title                 text NOT NULL,
    course_code           text NOT NULL,
    term                  text NOT NULL,
    description           text,
    created_by_user_id    bigint NOT NULL REFERENCES users(id) ON DELETE RESTRICT,
    start_date            date NOT NULL,
    end_date              date NOT NULL,
    is_active             boolean NOT NULL DEFAULT true,
    created_at            timestamptz NOT NULL DEFAULT now()
);

CREATE TABLE IF NOT EXISTS course_memberships (
    id                    bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    course_id             bigint NOT NULL REFERENCES courses(id) ON DELETE CASCADE,
    user_id               bigint NOT NULL REFERENCES users(id) ON DELETE CASCADE,
    role                  course_membership_role NOT NULL,
    status                course_membership_status NOT NULL DEFAULT 'active',
    joined_at             timestamptz NOT NULL DEFAULT now(),
    UNIQUE (course_id, user_id)
);

CREATE TABLE IF NOT EXISTS assignments (
    id                    bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    course_id             bigint NOT NULL REFERENCES courses(id) ON DELETE CASCADE,
    title                 text NOT NULL,
    description           text,
    assignment_type       assignment_type NOT NULL,
    total_points          integer NOT NULL CHECK (total_points >= 0),
    release_at            timestamptz NOT NULL,
    due_at                timestamptz NOT NULL,
    late_until            timestamptz,
    submission_type       text NOT NULL,
    allow_resubmissions   boolean NOT NULL DEFAULT false,
    max_attempt_resubmission integer NOT NULL DEFAULT 0,
    is_published          boolean NOT NULL DEFAULT false,
    created_by_user_id    bigint NOT NULL REFERENCES users(id) ON DELETE RESTRICT,
    created_at            timestamptz NOT NULL DEFAULT now(),
    updated_at            timestamptz NOT NULL DEFAULT now()
);

ALTER TABLE assignments
    ADD COLUMN IF NOT EXISTS rubric_json jsonb;

ALTER TABLE assignments
    ADD COLUMN IF NOT EXISTS questions_json jsonb;

CREATE TABLE IF NOT EXISTS assignment_rubric_items (
    id                    bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    assignment_id         bigint NOT NULL REFERENCES assignments(id) ON DELETE CASCADE,
    title                 text NOT NULL,
    description           text,
    max_points            integer NOT NULL CHECK (max_points >= 0),
    display_order         integer NOT NULL,
    grading_guidance      text,
    created_at            timestamptz NOT NULL DEFAULT now(),
    updated_at            timestamptz NOT NULL DEFAULT now()
);

CREATE TABLE IF NOT EXISTS submissions (
    id                    bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    assignment_id         bigint NOT NULL REFERENCES assignments(id) ON DELETE CASCADE,
    student_membership_id bigint NOT NULL REFERENCES course_memberships(id) ON DELETE CASCADE,
    attempt_number        integer NOT NULL DEFAULT 1,
    submitted_at          timestamptz NOT NULL DEFAULT now(),
    status                submission_status NOT NULL DEFAULT 'submitted',
    text_content          text,
    file_url              text,
    ai_processed_status   ai_processed_status NOT NULL DEFAULT 'awaiting',
    created_at            timestamptz NOT NULL DEFAULT now(),
    updated_at            timestamptz NOT NULL DEFAULT now()
);

CREATE TABLE IF NOT EXISTS submission_files (
    id                    bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    submission_id         bigint NOT NULL REFERENCES submissions(id) ON DELETE CASCADE,
    file_url              text NOT NULL,
    mime_type             text NOT NULL,
    file_size             integer CHECK (file_size >= 0),
    uploaded_at           timestamptz NOT NULL DEFAULT now()
);

CREATE TABLE IF NOT EXISTS grading_assignments (
    id                    bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    submission_id         bigint NOT NULL REFERENCES submissions(id) ON DELETE CASCADE,
    grader_membership_id  bigint NOT NULL REFERENCES course_memberships(id) ON DELETE CASCADE,
    status                grading_assignment_status NOT NULL DEFAULT 'pending',
    UNIQUE (submission_id, grader_membership_id)
);

CREATE TABLE IF NOT EXISTS grades (
    id                    bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    submission_id         bigint NOT NULL REFERENCES submissions(id) ON DELETE CASCADE,
    graded_by_membership_id bigint NOT NULL REFERENCES course_memberships(id) ON DELETE SET NULL,
    total_score           integer NOT NULL CHECK (total_score >= 0),
    overall_feedback      text,
    is_released_to_student boolean NOT NULL DEFAULT false,
    released_at           timestamptz,
    graded_at             timestamptz NOT NULL DEFAULT now(),
    created_at            timestamptz NOT NULL DEFAULT now(),
    updated_at            timestamptz NOT NULL DEFAULT now(),
    UNIQUE (submission_id)
);

CREATE TABLE IF NOT EXISTS rubric_scores (
    id                    bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    grade_id              bigint NOT NULL REFERENCES grades(id) ON DELETE CASCADE,
    rubric_item_id        bigint NOT NULL REFERENCES assignment_rubric_items(id) ON DELETE CASCADE,
    points_awarded        integer NOT NULL CHECK (points_awarded >= 0),
    comment               text,
    created_at            timestamptz NOT NULL DEFAULT now(),
    updated_at            timestamptz NOT NULL DEFAULT now(),
    UNIQUE (grade_id, rubric_item_id)
);

CREATE TABLE IF NOT EXISTS feedback_comments (
    id                    bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    submission_id         bigint NOT NULL REFERENCES submissions(id) ON DELETE CASCADE,
    author_membership_id  bigint NOT NULL REFERENCES course_memberships(id) ON DELETE CASCADE,
    rubric_item_id        bigint REFERENCES assignment_rubric_items(id) ON DELETE SET NULL,
    comment_type          comment_type NOT NULL DEFAULT 'summary',
    content               text NOT NULL,
    page_number           integer,
    anchor_data           jsonb,
    is_visible_to_student boolean NOT NULL DEFAULT true,
    created_at            timestamptz NOT NULL DEFAULT now(),
    updated_at            timestamptz NOT NULL DEFAULT now()
);

COMMIT;
